name = "example_pico"
description = "Example pico client project for the embedded-dashboard-console project"
version = "0.0.2"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]

tags = ["embedded", "rp2040"]
website = "https://github.com/hgrodriguez/edc_client_examples"

executables = ["example_pico"]

[gpr-set-externals]
#  I want all dependencies with full debug information
CORTEXM_BUILD_MODE="debug"
EDC_CLIENT_BUILD_MODE="debug"
PICO_BSP_BUILD_MODE="debug"
RP2040_HAL_BUILD_MODE="debug"
USB_EMBEDDED_BUILD_MODE="debug"

[[depends-on]]  # Added by alr
pico_bsp = "^1.3.0"  # Added by alr
[[depends-on]]  # Added by alr
edc_client = "^1.3.3"  # Added by alr
[[pins]]  # Added by alr
edc_client = { url='https://github.com/hgrodriguez/edc_client' }   # Added by alr
