name = "example_itsybitsy"
description = "Example itsybitsy client project for embedded-dashboard-console"
version = "0.0.2"
licenses = "BSD-3-Clause"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]
tags = ["embedded", "rp2040"]
website = "https://github.com/hgrodriguez/edc_client_examples"

executables = ["example_itsybitsy"]
[[depends-on]]  # Added by alr
pico_bsp = "^1.3.0"  # Added by alr
[[depends-on]]  # Added by alr
edc_client = "^1.3.3"  # Added by alr
[[pins]]  # Added by alr
edc_client = { url='https://github.com/hgrodriguez/edc_client' }   # Added by alr
[[depends-on]]  # Added by alr
itsybitsy_rp2040_bsp = "~0.1.0"  # Added by alr
